frequency: weekly
datasets:
  - name: "current"
    source: "tiros"
    query: >
      select
        sum(1) filter ( where m.type = 'KUBO' ) count_kubo,
        sum(1) filter ( where m.type = 'HTTP' ) count_http
      from measurements m
               inner join runs r on r.id = m.run_id
      where m.created_at >= {{ .StartOfWeek | timestamptz }} - '1 week'::interval
        and m.created_at < {{ .StartOfWeek | timestamptz }}
        and m.website = '{{ .Params.website }}'
      group by r.region, m.website;

scalars:
  - type: "number"
    name: "Kubo"
    dataset: "current"
    value: "count_kubo"
  - type: "number"
    name: "HTTP"
    dataset: "current"
    value: "count_http"

layout:
  margin:
    b: 1
    t: 1
  title:
    font:
      size: 10
    text: "Data: {{ .StartOfPreviousWeek | simpledate }} - {{ .EndOfPreviousWeek | simpledate }}"
    x: 0.01
    xanchor: left
    'y': 0.01
    yanchor: left