- directory: ./plotdefs-website
  output: "{{.PlotDefFilename}}-{{ .Params.website }}-{{ .Params.type }}-{{ .Params.region }}.json"
  variants:
    - website: filecoin.io
      type: KUBO
      region: eu-central-1
    - website: filecoin.io
      type: KUBO
      region: us-west-1
    - website: filecoin.io
      type: KUBO
      region: us-east-2
    - website: filecoin.io
      type: KUBO
      region: ap-southeast-2
    - website: filecoin.io
      type: KUBO
      region: sa-east-1
    - website: filecoin.io
      type: KUBO
      region: af-south-1
    - website: filecoin.io
      type: KUBO
      region: ap-south-1
    - website: filecoin.io
      type: HTTP
      region: eu-central-1
    - website: filecoin.io
      type: HTTP
      region: us-west-1
    - website: filecoin.io
      type: HTTP
      region: us-east-2
    - website: filecoin.io
      type: HTTP
      region: ap-southeast-2
    - website: filecoin.io
      type: HTTP
      region: sa-east-1
    - website: filecoin.io
      type: HTTP
      region: af-south-1
    - website: filecoin.io
      type: HTTP
      region: ap-south-1
    - website: libp2p.io
      type: KUBO
      region: eu-central-1
    - website: libp2p.io
      type: KUBO
      region: us-west-1
    - website: libp2p.io
      type: KUBO
      region: us-east-2
    - website: libp2p.io
      type: KUBO
      region: ap-southeast-2
    - website: libp2p.io
      type: KUBO
      region: sa-east-1
    - website: libp2p.io
      type: KUBO
      region: af-south-1
    - website: libp2p.io
      type: KUBO
      region: ap-south-1
    - website: libp2p.io
      type: HTTP
      region: eu-central-1
    - website: libp2p.io
      type: HTTP
      region: us-west-1
    - website: libp2p.io
      type: HTTP
      region: us-east-2
    - website: libp2p.io
      type: HTTP
      region: ap-southeast-2
    - website: libp2p.io
      type: HTTP
      region: sa-east-1
    - website: libp2p.io
      type: HTTP
      region: af-south-1
    - website: libp2p.io
      type: HTTP
      region: ap-south-1
    - website: ipld.io
      type: KUBO
      region: eu-central-1
    - website: ipld.io
      type: KUBO
      region: us-west-1
    - website: ipld.io
      type: KUBO
      region: us-east-2
    - website: ipld.io
      type: KUBO
      region: ap-southeast-2
    - website: ipld.io
      type: KUBO
      region: sa-east-1
    - website: ipld.io
      type: KUBO
      region: af-south-1
    - website: ipld.io
      type: KUBO
      region: ap-south-1
    - website: ipld.io
      type: HTTP
      region: eu-central-1
    - website: ipld.io
      type: HTTP
      region: us-west-1
    - website: ipld.io
      type: HTTP
      region: us-east-2
    - website: ipld.io
      type: HTTP
      region: ap-southeast-2
    - website: ipld.io
      type: HTTP
      region: sa-east-1
    - website: ipld.io
      type: HTTP
      region: af-south-1
    - website: ipld.io
      type: HTTP
      region: ap-south-1
    - website: protocol.ai
      type: KUBO
      region: eu-central-1
    - website: protocol.ai
      type: KUBO
      region: us-west-1
    - website: protocol.ai
      type: KUBO
      region: us-east-2
    - website: protocol.ai
      type: KUBO
      region: ap-southeast-2
    - website: protocol.ai
      type: KUBO
      region: sa-east-1
    - website: protocol.ai
      type: KUBO
      region: af-south-1
    - website: protocol.ai
      type: KUBO
      region: ap-south-1
    - website: protocol.ai
      type: HTTP
      region: eu-central-1
    - website: protocol.ai
      type: HTTP
      region: us-west-1
    - website: protocol.ai
      type: HTTP
      region: us-east-2
    - website: protocol.ai
      type: HTTP
      region: ap-southeast-2
    - website: protocol.ai
      type: HTTP
      region: sa-east-1
    - website: protocol.ai
      type: HTTP
      region: af-south-1
    - website: protocol.ai
      type: HTTP
      region: ap-south-1
    - website: docs.ipfs.tech
      type: KUBO
      region: eu-central-1
    - website: docs.ipfs.tech
      type: KUBO
      region: us-west-1
    - website: docs.ipfs.tech
      type: KUBO
      region: us-east-2
    - website: docs.ipfs.tech
      type: KUBO
      region: ap-southeast-2
    - website: docs.ipfs.tech
      type: KUBO
      region: sa-east-1
    - website: docs.ipfs.tech
      type: KUBO
      region: af-south-1
    - website: docs.ipfs.tech
      type: KUBO
      region: ap-south-1
    - website: docs.ipfs.tech
      type: HTTP
      region: eu-central-1
    - website: docs.ipfs.tech
      type: HTTP
      region: us-west-1
    - website: docs.ipfs.tech
      type: HTTP
      region: us-east-2
    - website: docs.ipfs.tech
      type: HTTP
      region: ap-southeast-2
    - website: docs.ipfs.tech
      type: HTTP
      region: sa-east-1
    - website: docs.ipfs.tech
      type: HTTP
      region: af-south-1
    - website: docs.ipfs.tech
      type: HTTP
      region: ap-south-1
    - website: tldr.filecoin.io
      type: KUBO
      region: eu-central-1
    - website: tldr.filecoin.io
      type: KUBO
      region: us-west-1
    - website: tldr.filecoin.io
      type: KUBO
      region: us-east-2
    - website: tldr.filecoin.io
      type: KUBO
      region: ap-southeast-2
    - website: tldr.filecoin.io
      type: KUBO
      region: sa-east-1
    - website: tldr.filecoin.io
      type: KUBO
      region: af-south-1
    - website: tldr.filecoin.io
      type: KUBO
      region: ap-south-1
    - website: tldr.filecoin.io
      type: HTTP
      region: eu-central-1
    - website: tldr.filecoin.io
      type: HTTP
      region: us-west-1
    - website: tldr.filecoin.io
      type: HTTP
      region: us-east-2
    - website: tldr.filecoin.io
      type: HTTP
      region: ap-southeast-2
    - website: tldr.filecoin.io
      type: HTTP
      region: sa-east-1
    - website: tldr.filecoin.io
      type: HTTP
      region: af-south-1
    - website: tldr.filecoin.io
      type: HTTP
      region: ap-south-1
    - website: green.filecoin.io
      type: KUBO
      region: eu-central-1
    - website: green.filecoin.io
      type: KUBO
      region: us-west-1
    - website: green.filecoin.io
      type: KUBO
      region: us-east-2
    - website: green.filecoin.io
      type: KUBO
      region: ap-southeast-2
    - website: green.filecoin.io
      type: KUBO
      region: sa-east-1
    - website: green.filecoin.io
      type: KUBO
      region: af-south-1
    - website: green.filecoin.io
      type: KUBO
      region: ap-south-1
    - website: green.filecoin.io
      type: HTTP
      region: eu-central-1
    - website: green.filecoin.io
      type: HTTP
      region: us-west-1
    - website: green.filecoin.io
      type: HTTP
      region: us-east-2
    - website: green.filecoin.io
      type: HTTP
      region: ap-southeast-2
    - website: green.filecoin.io
      type: HTTP
      region: sa-east-1
    - website: green.filecoin.io
      type: HTTP
      region: af-south-1
    - website: green.filecoin.io
      type: HTTP
      region: ap-south-1
    - website: drand.love
      type: KUBO
      region: eu-central-1
    - website: drand.love
      type: KUBO
      region: us-west-1
    - website: drand.love
      type: KUBO
      region: us-east-2
    - website: drand.love
      type: KUBO
      region: ap-southeast-2
    - website: drand.love
      type: KUBO
      region: sa-east-1
    - website: drand.love
      type: KUBO
      region: af-south-1
    - website: drand.love
      type: KUBO
      region: ap-south-1
    - website: drand.love
      type: HTTP
      region: eu-central-1
    - website: drand.love
      type: HTTP
      region: us-west-1
    - website: drand.love
      type: HTTP
      region: us-east-2
    - website: drand.love
      type: HTTP
      region: ap-southeast-2
    - website: drand.love
      type: HTTP
      region: sa-east-1
    - website: drand.love
      type: HTTP
      region: af-south-1
    - website: drand.love
      type: HTTP
      region: ap-south-1
    - website: web3.storage
      type: KUBO
      region: eu-central-1
    - website: web3.storage
      type: KUBO
      region: us-west-1
    - website: web3.storage
      type: KUBO
      region: us-east-2
    - website: web3.storage
      type: KUBO
      region: ap-southeast-2
    - website: web3.storage
      type: KUBO
      region: sa-east-1
    - website: web3.storage
      type: KUBO
      region: af-south-1
    - website: web3.storage
      type: KUBO
      region: ap-south-1
    - website: web3.storage
      type: HTTP
      region: eu-central-1
    - website: web3.storage
      type: HTTP
      region: us-west-1
    - website: web3.storage
      type: HTTP
      region: us-east-2
    - website: web3.storage
      type: HTTP
      region: ap-southeast-2
    - website: web3.storage
      type: HTTP
      region: sa-east-1
    - website: web3.storage
      type: HTTP
      region: af-south-1
    - website: web3.storage
      type: HTTP
      region: ap-south-1
    - website: consensuslab.world
      type: KUBO
      region: eu-central-1
    - website: consensuslab.world
      type: KUBO
      region: us-west-1
    - website: consensuslab.world
      type: KUBO
      region: us-east-2
    - website: consensuslab.world
      type: KUBO
      region: ap-southeast-2
    - website: consensuslab.world
      type: KUBO
      region: sa-east-1
    - website: consensuslab.world
      type: KUBO
      region: af-south-1
    - website: consensuslab.world
      type: KUBO
      region: ap-south-1
    - website: consensuslab.world
      type: HTTP
      region: eu-central-1
    - website: consensuslab.world
      type: HTTP
      region: us-west-1
    - website: consensuslab.world
      type: HTTP
      region: us-east-2
    - website: consensuslab.world
      type: HTTP
      region: ap-southeast-2
    - website: consensuslab.world
      type: HTTP
      region: sa-east-1
    - website: consensuslab.world
      type: HTTP
      region: af-south-1
    - website: consensuslab.world
      type: HTTP
      region: ap-south-1
    - website: strn.network
      type: KUBO
      region: eu-central-1
    - website: strn.network
      type: KUBO
      region: us-west-1
    - website: strn.network
      type: KUBO
      region: us-east-2
    - website: strn.network
      type: KUBO
      region: ap-southeast-2
    - website: strn.network
      type: KUBO
      region: sa-east-1
    - website: strn.network
      type: KUBO
      region: af-south-1
    - website: strn.network
      type: KUBO
      region: ap-south-1
    - website: strn.network
      type: HTTP
      region: eu-central-1
    - website: strn.network
      type: HTTP
      region: us-west-1
    - website: strn.network
      type: HTTP
      region: us-east-2
    - website: strn.network
      type: HTTP
      region: ap-southeast-2
    - website: strn.network
      type: HTTP
      region: sa-east-1
    - website: strn.network
      type: HTTP
      region: af-south-1
    - website: strn.network
      type: HTTP
      region: ap-south-1
    - website: research.protocol.ai
      type: KUBO
      region: eu-central-1
    - website: research.protocol.ai
      type: KUBO
      region: us-west-1
    - website: research.protocol.ai
      type: KUBO
      region: us-east-2
    - website: research.protocol.ai
      type: KUBO
      region: ap-southeast-2
    - website: research.protocol.ai
      type: KUBO
      region: sa-east-1
    - website: research.protocol.ai
      type: KUBO
      region: af-south-1
    - website: research.protocol.ai
      type: KUBO
      region: ap-south-1
    - website: research.protocol.ai
      type: HTTP
      region: eu-central-1
    - website: research.protocol.ai
      type: HTTP
      region: us-west-1
    - website: research.protocol.ai
      type: HTTP
      region: us-east-2
    - website: research.protocol.ai
      type: HTTP
      region: ap-southeast-2
    - website: research.protocol.ai
      type: HTTP
      region: sa-east-1
    - website: research.protocol.ai
      type: HTTP
      region: af-south-1
    - website: research.protocol.ai
      type: HTTP
      region: ap-south-1
    - website: ipfs.tech
      type: KUBO
      region: eu-central-1
    - website: ipfs.tech
      type: KUBO
      region: us-west-1
    - website: ipfs.tech
      type: KUBO
      region: us-east-2
    - website: ipfs.tech
      type: KUBO
      region: ap-southeast-2
    - website: ipfs.tech
      type: KUBO
      region: sa-east-1
    - website: ipfs.tech
      type: KUBO
      region: af-south-1
    - website: ipfs.tech
      type: KUBO
      region: ap-south-1
    - website: ipfs.tech
      type: HTTP
      region: eu-central-1
    - website: ipfs.tech
      type: HTTP
      region: us-west-1
    - website: ipfs.tech
      type: HTTP
      region: us-east-2
    - website: ipfs.tech
      type: HTTP
      region: ap-southeast-2
    - website: ipfs.tech
      type: HTTP
      region: sa-east-1
    - website: ipfs.tech
      type: HTTP
      region: af-south-1
    - website: ipfs.tech
      type: HTTP
      region: ap-south-1
    - website: blog.ipfs.tech
      type: KUBO
      region: eu-central-1
    - website: blog.ipfs.tech
      type: KUBO
      region: us-west-1
    - website: blog.ipfs.tech
      type: KUBO
      region: us-east-2
    - website: blog.ipfs.tech
      type: KUBO
      region: ap-southeast-2
    - website: blog.ipfs.tech
      type: KUBO
      region: sa-east-1
    - website: blog.ipfs.tech
      type: KUBO
      region: af-south-1
    - website: blog.ipfs.tech
      type: KUBO
      region: ap-south-1
    - website: blog.ipfs.tech
      type: HTTP
      region: eu-central-1
    - website: blog.ipfs.tech
      type: HTTP
      region: us-west-1
    - website: blog.ipfs.tech
      type: HTTP
      region: us-east-2
    - website: blog.ipfs.tech
      type: HTTP
      region: ap-southeast-2
    - website: blog.ipfs.tech
      type: HTTP
      region: sa-east-1
    - website: blog.ipfs.tech
      type: HTTP
      region: af-south-1
    - website: blog.ipfs.tech
      type: HTTP
      region: ap-south-1
    - website: docs.libp2p.io
      type: KUBO
      region: eu-central-1
    - website: docs.libp2p.io
      type: KUBO
      region: us-west-1
    - website: docs.libp2p.io
      type: KUBO
      region: us-east-2
    - website: docs.libp2p.io
      type: KUBO
      region: ap-southeast-2
    - website: docs.libp2p.io
      type: KUBO
      region: sa-east-1
    - website: docs.libp2p.io
      type: KUBO
      region: af-south-1
    - website: docs.libp2p.io
      type: KUBO
      region: ap-south-1
    - website: docs.libp2p.io
      type: HTTP
      region: eu-central-1
    - website: docs.libp2p.io
      type: HTTP
      region: us-west-1
    - website: docs.libp2p.io
      type: HTTP
      region: us-east-2
    - website: docs.libp2p.io
      type: HTTP
      region: ap-southeast-2
    - website: docs.libp2p.io
      type: HTTP
      region: sa-east-1
    - website: docs.libp2p.io
      type: HTTP
      region: af-south-1
    - website: docs.libp2p.io
      type: HTTP
      region: ap-south-1
    - website: blog.libp2p.io
      type: KUBO
      region: eu-central-1
    - website: blog.libp2p.io
      type: KUBO
      region: us-west-1
    - website: blog.libp2p.io
      type: KUBO
      region: us-east-2
    - website: blog.libp2p.io
      type: KUBO
      region: ap-southeast-2
    - website: blog.libp2p.io
      type: KUBO
      region: sa-east-1
    - website: blog.libp2p.io
      type: KUBO
      region: af-south-1
    - website: blog.libp2p.io
      type: KUBO
      region: ap-south-1
    - website: blog.libp2p.io
      type: HTTP
      region: eu-central-1
    - website: blog.libp2p.io
      type: HTTP
      region: us-west-1
    - website: blog.libp2p.io
      type: HTTP
      region: us-east-2
    - website: blog.libp2p.io
      type: HTTP
      region: ap-southeast-2
    - website: blog.libp2p.io
      type: HTTP
      region: sa-east-1
    - website: blog.libp2p.io
      type: HTTP
      region: af-south-1
    - website: blog.libp2p.io
      type: HTTP
      region: ap-south-1
    - website: en.wikipedia-on-ipfs.org/wiki
      type: KUBO
      region: eu-central-1
    - website: en.wikipedia-on-ipfs.org/wiki
      type: KUBO
      region: us-west-1
    - website: en.wikipedia-on-ipfs.org/wiki
      type: KUBO
      region: us-east-2
    - website: en.wikipedia-on-ipfs.org/wiki
      type: KUBO
      region: ap-southeast-2
    - website: en.wikipedia-on-ipfs.org/wiki
      type: KUBO
      region: sa-east-1
    - website: en.wikipedia-on-ipfs.org/wiki
      type: KUBO
      region: af-south-1
    - website: en.wikipedia-on-ipfs.org/wiki
      type: KUBO
      region: ap-south-1
    - website: en.wikipedia-on-ipfs.org/wiki
      type: HTTP
      region: eu-central-1
    - website: en.wikipedia-on-ipfs.org/wiki
      type: HTTP
      region: us-west-1
    - website: en.wikipedia-on-ipfs.org/wiki
      type: HTTP
      region: us-east-2
    - website: en.wikipedia-on-ipfs.org/wiki
      type: HTTP
      region: ap-southeast-2
    - website: en.wikipedia-on-ipfs.org/wiki
      type: HTTP
      region: sa-east-1
    - website: en.wikipedia-on-ipfs.org/wiki
      type: HTTP
      region: af-south-1
    - website: en.wikipedia-on-ipfs.org/wiki
      type: HTTP
      region: ap-south-1


#- directory: ./plotdefs-limited
#  output: "{{.PlotDefFilename}}.json"